/*
link: https://leetcode.com/problems/find-the-difference/description/

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

    char findTheDifference(std::string s, std::string t) {
        int sum_s = 0;
        int sum_t = 0;
        for (char c : s) {
            sum_s += c;
        }
        for (char c : t) {
            sum_t += c;
        }
        return (char)(sum_t - sum_s);
    }